/**
 * DÃ CHIẾN: LƯỚI CO GIÃN, LƯỢT THEO KHỞI ĐỘNG, SĨ KHÍ, VỠ TRẬN LAN TRUYỀN — Phần 10.
 *
 * Minigame thứ hai của dự án, và là chỗ `CombatChronicle` của Phần 9 được dùng
 * lại nguyên vẹn với `kind: 'battle'` (định dạng ấy ở `/src/systems/combat/`,
 * không ở đây; Phần 10 chỉ THÊM TRƯỜNG vào đó, không dựng định dạng riêng).
 *
 * Cửa vào của phần còn lại của game:
 *   `createBattle`           dựng một trận từ hai bản khai quân
 *   `issueWingOrders`        ra lệnh cho các cánh, qua ma sát 3d6 của mục 3
 *   `playRound`              một vòng: người chơi đã bấm, engine lo phần còn lại
 *   `autoBattle`             đánh trọn một trận không có người — test và mô phỏng
 *   `settleAftermath`        truy kích, tù binh, tiền chuộc, thương binh (mục 12)
 *   `chargeIn` · `resolveCharge`  người chơi tự thân lâm trận (mục 11)
 *   `buildChronicle` · `chronicleFor`  biên niên cho AI viết diễn biến (mục 13)
 *   `registerBattleSources`  cắm mười một nguồn modifier vào registry của Phần 5
 *
 * Xem `README.md` cùng thư mục cho hợp đồng đọc/ghi state.
 */

export {
  BattleDataError,
  allBattleTerrain,
  allFields,
  allFormations,
  allTimesOfDay,
  allUnitTypes,
  allWeather,
  battleConfig,
  battleTerrainOf,
  commandOf,
  commandRows,
  counterRows,
  defaultField,
  defaultTimeOfDay,
  defaultWeather,
  defenceBand,
  fieldOf,
  formationChange,
  formationName,
  formationOf,
  gridConfig,
  nightVisionTag,
  noDaylightPursuitTag,
  tagName,
  timeOfDayOf,
  unitTypeOf,
  unitTypesFor,
  weatherOf,
  type BattleConfig,
  type BattleTerrain,
  type BattlefieldTemplate,
  type CommandRow,
  type CommandScope,
  type Counter,
  type FieldFeature,
  type Formation,
  type FormationChange,
  type GridConfig,
  type TimeOfDay,
  type UnitType,
  type Weather,
} from './data';

export {
  ARC_LABELS,
  DIR_NAMES,
  DIR_VECTORS,
  arcOf,
  cellMetersFor,
  cellsFor,
  concealmentBetween,
  dirGap,
  dirName,
  directionTo,
  distance,
  elevationAt,
  fleeTarget,
  frontageAt,
  generateField,
  gridSideFor,
  inBounds,
  menPerPiece,
  metersFor,
  passable,
  piecesPerSide,
  planGrid,
  sameCell,
  stepToward,
  terrainAt,
  turnBy,
  type Arc,
  type BattleGrid,
  type Cell,
  type Dir8,
  type GridPlan,
  type StepOutcome,
} from './grid';

export {
  ARC_SOURCE_ID,
  BATTLE_SOURCES,
  CLASH_DOMAIN,
  COHESION_SOURCE_ID,
  COUNTER_SOURCE_ID,
  FATIGUE_SOURCE_ID,
  FORMATION_SOURCE_ID,
  GROUND_SOURCE_ID,
  LOYALTY_SOURCE_ID,
  MORALE_DOMAIN,
  MORALE_SOURCE_ID,
  NIGHT_SOURCE_ID,
  ORDER_DOMAIN,
  QUALITY_SOURCE_ID,
  VOLLEY_DOMAIN,
  WEATHER_SOURCE_ID,
  commandFactor,
  commandView,
  counterLines,
  engagement,
  publishCommand,
  publishEngagement,
  registerBattleSources,
  seesInDark,
  sightFactor,
  type CommandView,
  type CounterLine,
  type Engagement,
  type EngagementView,
} from './modifiers';

export {
  baseDice,
  canShoot,
  defenceBreakdown,
  foeTagsOf,
  rangeInCells,
  resolveClash,
  type ClashOutcome,
  type DefenceBreakdown,
  type DefenceLine,
} from './clash';

export {
  nearestEnemy,
  opportunityTargets,
  rollInitiative,
  rollInitiativeFor,
  type InitiativePart,
  type InitiativeRoll,
  type Reaction,
} from './initiative';

export {
  adjustMorale,
  aliveUnit,
  ambientMorale,
  breakUnit,
  commanderFell,
  moraleCheck,
  propagateRout,
  refreshState,
  shock,
  stateFromMorale,
  stateLabel,
  tickRout,
  type MoraleOutcome,
  type RoutSpread,
} from './morale';

export {
  buildCommand,
  centerEngaged,
  commandsWholeArmy,
  fieldOrderFor,
  issueOrder,
  markDisobedience,
  obedienceOutcome,
  officerUnits,
  orderLabel,
  setsStrategy,
  violatesOrder,
  type CommandSetup,
  type ObedienceOutcome,
  type OrderOutcome,
} from './command';

export {
  ACTION_LABELS,
  antiCavalryFormation,
  bestShootTarget,
  canCharge,
  cavalryClosing,
  chooseUnitAction,
  cohesionTick,
  fatigueTick,
  movePoints,
  routMove,
  stillFighting,
  type TacticContext,
  type UnitAction,
  type UnitActionKind,
} from './tactics';

export {
  BATTLE_STREAM,
  BattleError,
  ENDINGS,
  MAX_ROUNDS,
  autoBattle,
  buildChronicle,
  chronicleFor,
  cloneBattle,
  createBattle,
  issueWingOrders,
  officerKilled,
  orderFor,
  playRound,
  type BattleSetup,
  type CompositionEntry,
  type ForceSpec,
  type OfficerSpec,
  type RoundResult,
} from './engine';

export {
  blessing,
  captureFate,
  pursue,
  rallySpeech,
  scout,
  settleAftermath,
  type CaptureFate,
  type PrepReport,
  type PursuitReport,
} from './aftermath';

export {
  canChargeIn,
  championFor,
  chargeIn,
  playerFell,
  playerFighter,
  resolveCharge,
  type ChargeIn,
  type ChargeResult,
} from './duel-link';

export {
  ORDER_EFFECT_LABELS,
  ORDER_IDS,
  ORDER_LABELS,
  TEMPERAMENT_LABELS,
  UNIT_STATE_LABELS,
  WINGS,
  WING_LABELS,
  averageMorale,
  controllable,
  officerById,
  onField,
  otherSide,
  playerCommands,
  standingShare,
  strengthOf,
  unitById,
  unitsOf,
  wingUnits,
  type Aftermath,
  type BattleCheck,
  type BattleLogLine,
  type BattleState,
  type BattleUnit,
  type CommandState,
  type FieldOrder,
  type IssuedOrder,
  type Officer,
  type OrderEffect,
  type OrderId,
  type Prisoner,
  type SideId,
  type Temperament,
  type UnitStateId,
  type WingId,
} from './types';
