/**
 * NHÂN VẬT — Phần 6.
 *
 * 12 chỉ số 4/4/4, chủng tộc nạp từ data, xuất thân chỉ ảnh hưởng vạch xuất
 * phát, và luồng tạo nhân vật 9 bước quay lui được.
 *
 * Cửa vào của phần còn lại của game:
 *   `characterOf`              đọc nhân vật hiện tại
 *   `domainBase` / `skillBase` `CheckSpec.base` cho một phép kiểm
 *   `registerCharacterSources` cắm chỉ số và đặc tính vào registry của Phần 5
 *   `newDraft` … `buildInitialState`  luồng 9 bước
 *
 * Xem `README.md` cùng thư mục cho hợp đồng đọc/ghi state.
 */

export {
  STATS,
  STAT_GROUPS,
  STAT_IDS,
  STAT_MAX,
  STAT_MIN,
  addStatBlocks,
  clampStat,
  d20Mod,
  emptyStatBlock,
  isStatId,
  skillContribution,
  skillPercent,
  statBandLabel,
  statContribution,
  statsIn,
  threeD6Target,
  type StatBlock,
  type StatGroupId,
  type StatId,
  type StatInfo,
} from './stats';

export {
  ATTITUDE_BASE,
  RaceDataError,
  ageStageOf,
  ageStages,
  ageStatShift,
  allRaces,
  appearanceCommon,
  attitudeLabel,
  attitudeTable,
  creationAgeRange,
  effectiveAge,
  learnFactor,
  nationIds,
  nationName,
  playableRaces,
  raceAttitudeTo,
  raceGroups,
  raceName,
  raceOf,
  startAgeRange,
  statCapDefault,
  statCapOf,
  statCapsOf,
  statModsOf,
  traitsOf,
  type AgeStage,
  type Race,
  type RaceAppearance,
} from './races';

export {
  SkillDataError,
  allSkills,
  domainOfSkill,
  fallbackSkill,
  groupName,
  skillForDomain,
  skillGroups,
  skillName,
  skillOf,
  skillsInGroup,
  statForDomain,
  type Skill,
  type SkillGroup,
} from './skills';

export {
  OriginDataError,
  ageSkillBonus,
  allBirthOrders,
  allLineageStates,
  allOrigins,
  birthOrderOf,
  lineageStateOf,
  originName,
  originOf,
  pointBuy,
  relationKinds,
  startingLine,
  statBudget,
  statCost,
  statStepCost,
  skillBudget,
  wealthCoins,
  wealthLabel,
  type BirthOrder,
  type LineageState,
  type Origin,
  type PointBuy,
  type StartingLine,
} from './origins';

export {
  TraitDataError,
  allTraits,
  traitName,
  traitOf,
  type Trait,
  type TraitEffect,
} from './traits';

export { effectApplies, effectSchema, scaleIntensity, type Effect } from './effects';

export {
  BeliefDataError,
  allCultures,
  allReligions,
  beliefEffects,
  cultureName,
  cultureOf,
  culturesForRace,
  religionName,
  religionOf,
  religionsForRace,
  suggestedCulture,
  suggestedReligion,
  type Culture,
  type Religion,
} from './beliefs';

export {
  DEFAULT_QUALITY,
  GearDataError,
  allGear,
  carry,
  coveredRegions,
  gearEffect,
  gearKinds,
  gearMaterials,
  gearName,
  gearOf,
  gearOfKind,
  gearPrice,
  gearQualities,
  gearSlots,
  gearWeight,
  materialName,
  qualityName,
  qualityOf,
  slotName,
  type CarriedGear,
  type GearItem,
  type GearQuality,
} from './gear';

export {
  CLAIM_KINDS,
  HouseDataError,
  allHouses,
  claimLabel,
  claimStrengthFor,
  claimStrengthName,
  claimStrengths,
  claimsFromHouse,
  alliesOf,
  houseHasLoreHead,
  houseHeadName,
  houseName,
  houseOf,
  houseRankName,
  houseTiers,
  housesByGroup,
  housesForOrigin,
  housesForOriginAndRace,
  loreEntryOf,
  lorePeople,
  lorePersonName,
  originHasHouses,
  relatedHouses,
  rivalsOf,
  searchHouses,
  type ClaimKind,
  type DerivedClaim,
  type House,
  type LoreEntryDetails,
  type LorePerson,
} from './houses';

export {
  PossessionDataError,
  fiefIdFor,
  fiefObligations,
  fiefTitleName,
  fiefTitleOf,
  fiefTitles,
  highestRank,
  holdingIdFor,
  holdingRoleOf,
  holdingRoleName,
  holdingRoles,
  knownSettlements,
  obligationOf,
  obligationName,
  realmRoleOf,
  realmRoleName,
  realmRoles,
  settlementTierName,
  settlementTierOf,
  settlementTiers,
  settlementsWithin,
  slugify,
  type FiefTitle,
  type KnownSettlement,
  type SettlementTier,
} from './possessions';

export {
  characterOf,
  characterSchema,
  characterSlice,
  statValueOf,
  trainingOf,
  type Appearance,
  type CharacterState,
  type FamilyMember,
  type Scar,
  type Secret,
} from './slice';

export {
  domainBase,
  freeformBase,
  skillBase,
  skillPercentOf,
  trainingLevel,
} from './base';

export {
  AGE_SOURCE_ID,
  CULTURE_SOURCE_ID,
  GEAR_SOURCE_ID,
  RELIGION_SOURCE_ID,
  STAT_SOURCE_ID,
  TRAIT_SOURCE_ID,
  ageSource,
  cultureSource,
  gearSource,
  registerCharacterSources,
  religionSource,
  statSource,
  traitSource,
} from './modifiers';

export {
  FAMILY_RELATION_LABELS,
  familyRelationLabel,
  generateFamily,
  generateOutsideRelations,
  generateSecrets,
  randomAppearance,
  randomFamilyName,
  randomFullName,
  randomGivenName,
  randomScar,
  type OutsideRelation,
  type Sex,
} from './generate';

export {
  CREATION_STEPS,
  CreationError,
  UNNAMED,
  ageSkillPoints,
  allIssues,
  holdingLabel,
  buildInitialState,
  canLowerStat,
  canRaiseSkill,
  canRaiseStat,
  draftAgeStage,
  draftSkillPercent,
  finalStats,
  finalize,
  fullName,
  lowerSkill,
  lowerStat,
  newDraft,
  openingSceneAction,
  raiseSkill,
  raiseStat,
  recomputeClaims,
  setFamilyHouse,
  withHouse,
  rollAppearance,
  rollFamily,
  rollNames,
  rollSecrets,
  skillPointBudget,
  skillPointsLeft,
  skillPointsSpent,
  skillsAffectedBy,
  statPointsLeft,
  statPointsSpent,
  stepHints,
  stepIndex,
  stepIssues,
  withAge,
  withOrigin,
  withRace,
  type CharacterDraft,
  type DraftAllegiance,
  type DraftFief,
  type DraftHolding,
  type CreationStepId,
} from './create';
